### ISSUE TITLE
Doesn't throw CssSyntaxError when using @babel/core@7.0.0-rc.2

### ISSUE THREAD

**Issue by shinnn** [gucong3000/postcss-jsx#30]
```js
'use strict';

const {parse} = require('postcss-jsx');

parse('styled.a`"`;', {from: 'file.js'});
```

When you have installed `@babel/core@7.0.0-rc.1`, the script above throws the following error:

```console
$ node run.js

/Users/shinnn/example/node_modules/postcss-syntax/parse-style.js:66
				throw this.error(error);
				^
CssSyntaxError: /Users/shinnn/example/file.js:1:10: Unclosed string
    at Input.error (/Users/shinnn/example/node_modules/postcss/lib/input.js:124:16)
    at unclosed (/Users/shinnn/example/node_modules/postcss/lib/tokenize.js:59:17)
    at Object.nextToken (/Users/shinnn/example/node_modules/postcss/lib/tokenize.js:176:15)
    at Parser.parse (/Users/shinnn/example/node_modules/postcss/lib/parser.js:55:30)
    at Object.parse (/Users/shinnn/example/node_modules/postcss/lib/parse.js:19:12)
    at LocalFixer.parse (/Users/shinnn/example/node_modules/postcss-syntax/parse-style.js:57:18)
    at parseStyle (/Users/shinnn/example/node_modules/postcss-syntax/parse-style.js:89:39)
    at styles.sort.forEach.style (/Users/shinnn/example/node_modules/postcss-syntax/parse-style.js:104:17)
    at Array.forEach (<anonymous>)
    at parseStyle (/Users/shinnn/example/node_modules/postcss-syntax/parse-style.js:103:6)
```

This is an expected behavior because `"` is an invalid CSS.

However, if you have installed `@babel/core@7.0.0-rc.2`, the same script doesn't throw any errors.

The currently effective workaround is to change `package.json#L44` https://github.com/gucong3000/postcss-jsx/blob/dd851fdf675ce8e41c77bb01765d98fff4efc4b0/package.json#L44 like the following:

```diff
- "@babel/core": "^7.0.0-rc.1"
+ "@babel/core": "7.0.0-rc.1"
```

**Comment by gucong3000** [comment]
Fixed in master branch
